import "./globals.css";
import { Footer, Header } from "../components";

export const metadata = {
	title: 'Jewelry Shop',
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className="relative">
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	)
}
